[package]
name = "trait1"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mockall = "0.11"
async-trait = "0.1"

[dev-dependencies]
mockall_double = "0.2"